version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - kong-net
    ports:
      - 8080:8080